version: '3'
services:
  app1:
    build: .
    environment:
      - APPNAME=App1
    ports:
      - "3001:3000"

  app2:
    build: .
    environment:
      - APPNAME=App2
    ports:
      - "3002:3000"

  app3:
    build: .
    environment:
      - APPNAME=App3
    ports:
      - "3003:3000"
